In [2]:
# https://numpy.org/doc/stable/user/absolute_beginners.html 

import numpy as np
import random

In [3]:
height = np.array([1.87, 1.87, 1.82, 1.91, 1.90, 1.85])
weight = np.array([81.65, 97.52, 95.25, 92.98, 86.18, 88.45])

In [4]:
rand = np.random.randint(0,100, 10) #generates 10 nums btwn. 0 and 100
print(rand)

[15 32 27 21 42 54  4 38 43 24]


In [19]:
print(np.sort(height)[::-1])  #sorts and then reverses
print(np.sort(weight))

[1.91 1.9  1.87 1.87 1.85 1.82]
[81.65 86.18 88.45 92.98 95.25 97.52]


In [21]:
"""
axis = 0 --> cols (x-coord)
axis = 1 --> rows (y-coord)
axis = 2 --> (z-coord)

if we do axis = 1 for the above concat operation, we will get an error because x has 2 rows while y only has 1. 
they need to be equal

however, for axis = 0, both x and y have 2 cols, therefore this is valid
"""

x = np.array([[1, 2], [3, 4]])
y = np.array([[5,6]])
np.concatenate((x, y), axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [22]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [25]:
five_up = (a >= 5)
print(five_up)
print(a[five_up])

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]
[ 5  6  7  8  9 10 11 12]
