In [11]:
import numpy as np
import random

In [12]:
height = np.array([1.87, 1.87, 1.82, 1.91, 1.90, 1.85])
weight = np.array([81.65, 97.52, 95.25, 92.98, 86.18, 88.45])

In [16]:
rand = np.random.randint(0,100, 10) #generates 10 nums btwn. 0 and 100
print(rand)

[34 20 63 61 25 33 19  7 59 47]


In [18]:
print(np.sort(height)[::-1]) #sorts and then reverses
print(np.sort(weight))

[1.91 1.87 1.85]
[81.65 86.18 88.45 92.98 95.25 97.52]
