In [11]:
import numpy as np
import random

In [12]:
height = np.array([1.87, 1.87, 1.82, 1.91, 1.90, 1.85])
weight = np.array([81.65, 97.52, 95.25, 92.98, 86.18, 88.45])

In [16]:
rand = np.random.randint(0,100, 10) #generates 10 nums btwn. 0 and 100
print(rand)

[34 20 63 61 25 33 19  7 59 47]


In [18]:
print(np.sort(height)[::-1]) #sorts and then reverses
print(np.sort(weight))

[1.91 1.87 1.85]
[81.65 86.18 88.45 92.98 95.25 97.52]


In [24]:
array = np.zeros(shape = 500)
for i in range(500):
    rand_num = random.randint(0, 100)
    array[i] = rand_num
print(array)

[100.  68.   8.  67. 100.  28.  79.  85.  67.  38.  50.   5.  37.  59.
  38.  38.   3.  15.  25.  22.  85.  55.  81.  49.  31.  82.  91.  37.
  58.  40.  30.  85.  43.  25.  40.  97.  52.  36.   8.  60.  50.  47.
  31.  19.   2.  68.  62.  28.  52.   1.  47.  98.  95.  51.   0.  71.
  93.  79.  91.  43.  67.  81.   6.  94.  14.  38.  99.  99.  77.  31.
  57.  76.  98.  61.  58.  30.  52.  50.  58.  31.  90.  27.  68.  63.
  54.  39.  15.  55.  32.  22.  29.  78.  54.  35.  57.  39.   1.  45.
  36.   6.  32.  50.  48.  28.  76.  57.  15.   6.  97.  64.  20.  19.
  94.  89.  34.  47.  48.  29.  59.  11.  70.  81.  11.  56.  22.  13.
  90.  29.  58.  96.  89.  54.  92.  38.  71.  78.  34.  72.  81.  56.
  42.  81.  83.  49.  62.   9.  18.  17.  11.  65.  28.  65.   4.  58.
  28.  16.   2.  72.  95.   8.  26.  20.  54.  32.  70.   4.  78.  16.
  32.  63.  16.  84.  89.  39.  43.  12.  64.  31.  89.  58.  19.  88.
  58.  72.  40.  65.  49.  71.  76.  69.  52.  55.  88.  32.  31.  56.
  76. 

In [33]:
def bubblesort(arr):
    for i in range(len(arr)):
        still_swapping = False
        for j in range(len(arr)-1):
            if arr[j] > arr[j+1] :
                arr[j], arr[j+1] = arr[j+1], arr[j]
                still_swapping = True
        if still_swapping == False:
            #array has now been properly sorted
            break

In [34]:
def selectionsort(arr):
    """
    logic: find index of minimum value from unsorted portion of arr and puts it at the start
    """ 
    for i in range(len(arr)):
        min_idx = i
        for j in range(i+1, len(arr)):
            if arr[min_idx] > arr[j]:
                min_idx = j     
        arr[i], arr[min_idx] = arr[min_idx], arr[i]

In [36]:
bubblesort(array)
selectionsort(array)
print(array)

[  0.   0.   0.   0.   1.   1.   1.   1.   1.   1.   2.   2.   2.   2.
   2.   2.   3.   3.   4.   4.   4.   4.   4.   5.   5.   5.   5.   5.
   6.   6.   6.   6.   6.   7.   7.   7.   8.   8.   8.   8.   9.   9.
   9.   9.   9.  10.  10.  11.  11.  11.  11.  11.  11.  12.  13.  13.
  13.  14.  14.  15.  15.  15.  15.  15.  16.  16.  16.  16.  16.  17.
  17.  17.  17.  18.  18.  19.  19.  19.  19.  19.  20.  20.  20.  20.
  20.  20.  21.  21.  21.  21.  21.  22.  22.  22.  22.  22.  22.  23.
  23.  23.  23.  23.  23.  24.  24.  24.  24.  24.  25.  25.  25.  25.
  25.  25.  26.  26.  26.  26.  26.  27.  27.  27.  28.  28.  28.  28.
  28.  28.  28.  28.  29.  29.  29.  29.  29.  30.  30.  30.  30.  30.
  31.  31.  31.  31.  31.  31.  31.  31.  31.  31.  32.  32.  32.  32.
  32.  32.  32.  32.  32.  32.  33.  33.  34.  34.  35.  35.  35.  35.
  36.  36.  36.  36.  36.  36.  36.  36.  37.  37.  37.  37.  38.  38.
  38.  38.  38.  38.  38.  38.  39.  39.  39.  39.  39.  39.  40.  40.
  40. 